///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: musica/molusk.aks
/// Generation time: dom 18 oct 2020 21:41:28 CEST
///

/// Song 'molusk' metadata macros
#define molusk_address  0x1D4D
#define molusk_size     8883
#define molusk_end      0x3fff

/// Song 'molusk' array declaration
extern void molusk[molusk_size];
